packages:
  - packages/*
  - examples

allowBuilds:
  esbuild: false
  simple-git-hooks: false

ignoredBuiltDependencies:
  - esbuild
  - simple-git-hooks

updateConfig:
  ignoreDependencies:
    - '@types/node'
